name: C++ CI (Sniffer Build)

on:
  push:
    branches: [ "main" , "adding-sniffer"]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: C++ Derleyici Kurulumu
      run: sudo apt-get update && sudo apt-get install -y build-essential
      
    - name: Sniffer'i Derle
      # Eger dosyanizi src/sniffer/ icine koyduysaniz yolu ona gore guncelleyin.
      # Kok dizindeyse dogrudan g++ sniffer.cpp -o sniffer yazin.
      run: g++ sniffer.cpp -o sniffer